service: adcomfort-nodejs-sl

custom:
  secrets: ${file(secrets.json)}
  apigwBinary:
    types:
      - '*/*'

package:
  exclude:
    - node_modules/.cache/**
    - node_modules/.bin/**

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.secrets.NODE_ENV}
  region: eu-west-2
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    DB: ${self:custom.secrets.DB}

functions:
  app:
    handler: server.run
    events:
      - http:
          path: /
          method: ANY
          cors: true
          contentHandling: CONVERT_TO_BINARY
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
          contentHandling: CONVERT_TO_BINARY

plugins:
  - serverless-offline
  - serverless-apigw-binary
  - serverless-apigwy-binary